FROM node:lts-alpine3.22
WORKDIR /app
COPY ./notion-mcp-server-main.zip /app
RUN unzip notion-mcp-server-main.zip
WORKDIR /app/notion-mcp-server-main
RUN npm install
RUN npm run build
CMD ["/app/notion-mcp-server-main/bin/cli.mjs", "--transport", "http", "--port", "3000"]
